--- 
title: "something something something"
author: "Max Kuhn"
date: "`r Sys.Date()`"
documentclass: krantz
classoption: numberinsequence
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
colorlinks: yes
graphics: yes
---

# Preface {-}

A note to reviewers: this book is being created using [bookdown](https://bookdown.org) for both HTML and PDF (via LaTeX). Aesthetic aspects of the content, such as the sizing and placement of figures, will be optimized at once the content has been finalized. 

The R packages and versions used in this text are:

```{r load, include = FALSE, warning=FALSE,message=FALSE}
library(sessioninfo)
library(bookdown)
library(rmarkdown)
```
```{r session}
sessionInfo()

rmarkdown::pandoc_version()
```
```r
> system('pdflatex --version')
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017)
kpathsea version 6.2.3
Copyright 2017 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.29; using libpng 1.6.29
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 3.04
```

\mainmatter

some stuff here


